module.exports = {
    batterys: [
        {
            image: '/images/picture-4.jpeg',
            type: 'Non-rechargeable',
            family: 'Li Primary',
            chemistry: 'Lithium Manganese Dioxide',
            supplier: 'GP',
            name: 'CR123A',
            outdoor: 'N',
            capacity: 1500,
            maxCurrent: 10,
            model: '',
            weight: 17,
            height: 34.5,
            diameter: 16.8,
            nominalVoltage: 3.0,
            minTemperature: -40,
            maxTemperature: 60,
        },
        {
            image: '/images/picture-22.jpeg',
            type: 'Non-rechargeable',
            family: 'Li Primary',
            chemistry: 'Lithium Manganese Dioxide',
            supplier: 'GP',
            name: 'CR2',
            outdoor: 'N',
            capacity: 800,
            maxCurrent: 10,
            model: '',
            weight: 10,
            height: 26.5,
            diameter: 15.3,
            nominalVoltage: 3.0,
            minTemperature: -40,
            maxTemperature: 60,
        },
        {
            image: '/images/picture-33.jpeg',
            type: 'Non-rechargeable',
            family: 'Li Primary',
            chemistry: 'Lithium Manganese Dioxide',
            supplier: 'GP',
            name: 'CR2/3A',
            outdoor: 'Y',
            capacity: 1650,
            maxCurrent: 1500,
            model: '',
            weight: 16,
            height: 33.5,
            diameter: 17,
            nominalVoltage: 3.0,
            minTemperature: -40,
            maxTemperature: 60,
        },
        {
            image: '/images/picture-44.jpeg',
            type: 'Non-rechargeable',
            family: 'Li Primary',
            chemistry: 'Lithium Manganese Dioxide',
            supplier: 'GP',
            name: 'CR17450',
            outdoor: 'Y',
            capacity: 2400,
            maxCurrent: 1500,
            model: '',
            weight: 22,
            height: 45,
            diameter: 17,
            nominalVoltage: 3.0,
            minTemperature: -40,
            maxTemperature: 60,
        },
        {
            image: '/images/picture-55.jpeg',
            type: 'Non-rechargeable',
            family: 'Li Primary',
            chemistry: 'Lithium Thionyl Chloride',
            supplier: 'Xeno',
            name: 'XL-050F',
            outdoor: 'Y',
            capacity: 1200,
            maxCurrent: 30,
            model: '1/2AA',
            weight: 9,
            height: 25.1,
            diameter: 14.5,
            nominalVoltage: 3.6,
            minTemperature: -55,
            maxTemperature: 85,
        },
        {
            image: '/images/picture-66.jpeg',
            type: 'Non-rechargeable',
            family: 'Li Primary',
            chemistry: 'Lithium Thionyl Chloride',
            supplier: 'Xeno',
            name: 'XL-060F',
            outdoor: 'Y',
            capacity: 2400,
            maxCurrent: 60,
            model: 'AA',
            weight: 17,
            height: 50.1,
            diameter: 14.5,
            nominalVoltage: 3.6,
            minTemperature: -55,
            maxTemperature: 85,
        },
        {
            image: '/images/picture-77.jpeg',
            type: 'Non-rechargeable',
            family: 'Li Primary',
            chemistry: 'Lithium Thionyl Chloride',
            supplier: 'Xeno',
            name: 'XL-100F',
            outdoor: 'Y',
            capacity: 3600,
            maxCurrent: 100,
            model: 'A',
            weight: 24,
            height: 50.7,
            diameter: 17,
            nominalVoltage: 3.6,
            minTemperature: -55,
            maxTemperature: 85,
        },
        {
            image: '/images/picture-88.jpeg',
            type: 'Non-rechargeable',
            family: 'Li Primary',
            chemistry: 'Lithium Thionyl Chloride',
            supplier: 'Xeno',
            name: 'XL-205F',
            outdoor: 'Y',
            capacity: 19000,
            maxCurrent: 230,
            model: 'D',
            weight: 98,
            height: 60,
            diameter: 33.3,
            nominalVoltage: 3.6,
            minTemperature: -55,
            maxTemperature: 85,
        },
        {
            image: '/images/picture-99.jpeg',
            type: 'Rechargeable',
            family: 'Li Secondary',
            chemistry: 'Lithium Ferro Phosphate',
            supplier: 'GP',
            name: '18650',
            outdoor: 'N',
            capacity: 1500,
            maxCurrent: 3000,
            model: '',
            weight: 45,
            height: 65.5,
            diameter: 18.4,
            nominalVoltage: 3.2,
            minTemperature: -20,
            maxTemperature: 60,
        },
        {
            image: '/images/picture-10.jpeg',
            type: 'Rechargeable',
            family: 'Li Secondary',
            chemistry: 'Lithium Ferro Phosphate',
            supplier: 'GP',
            name: '1633-81S',
            outdoor: 'N',
            capacity: 810,
            maxCurrent: 1620,
            model: '',
            weight: 21,
            height: 33,
            diameter: 16.5,
            nominalVoltage: 3.8,
            minTemperature: -20,
            maxTemperature: 60,
        },
        {
            image: '/images/picture-11.jpeg',
            type: 'Rechargeable',
            family: 'Li Secondary',
            chemistry: 'Lithium Ferro Phosphate',
            supplier: 'GP',
            name: '1022-L15',
            outdoor: 'N',
            capacity: 155,
            maxCurrent: 124,
            model: '',
            weight: 4.2,
            height: 21.9,
            diameter: 10.4,
            nominalVoltage: 3.8,
            minTemperature: -20,
            maxTemperature: 60,
        },
        {
            image: '/images/picture-12.jpeg',
            type: 'Rechargeable',
            family: 'Li Secondary',
            chemistry: 'Lithium Ferro Phosphate',
            supplier: 'GP',
            name: '1010-06S',
            outdoor: 'N',
            capacity: 60,
            maxCurrent: 120,
            model: '',
            weight: 2.2,
            height: 10.2,
            diameter: 10.4,
            nominalVoltage: 3.8,
            minTemperature: -20,
            maxTemperature: 60,
        },
        {
            image: '/images/picture-13.jpeg',
            type: 'Rechargeable',
            family: 'NiMH',
            chemistry: 'NiMH',
            supplier: 'GP',
            name: '60AAHT4',
            outdoor: 'Y',
            capacity: 600,
            maxCurrent: 1000,
            model: 'AAA',
            weight: 14,
            height: 43.7,
            diameter: 10.5,
            nominalVoltage: 1.2,
            minTemperature: -35,
            maxTemperature: 85,
        },
        {
            image: '/images/picture-14.jpeg',
            type: 'Rechargeable',
            family: 'NiMH',
            chemistry: 'NiMH',
            supplier: 'GP',
            name: '125AAMT',
            outdoor: 'Y',
            capacity: 1250,
            maxCurrent: 625,
            model: 'AA',
            weight: 24,
            height: 48.2,
            diameter: 14.4,
            nominalVoltage: 1.2,
            minTemperature: -20,
            maxTemperature: 70,
        },
        {
            image: '/images/picture-15.jpeg',
            type: 'Rechargeable',
            family: 'NiMH',
            chemistry: 'NiMH',
            supplier: 'GP',
            name: '210AFHT',
            outdoor: 'Y',
            capacity: 3700,
            maxCurrent: 1850,
            model: 'AF',
            weight: 60,
            height: 69,
            diameter: 17.5,
            nominalVoltage: 1.2,
            minTemperature: -20,
            maxTemperature: 70,
        },
        {
            image: '/images/picture-16.jpeg',
            type: 'Rechargeable',
            family: 'NiMH',
            chemistry: 'NiMH',
            supplier: 'GP',
            name: '400LALHT',
            outdoor: 'Y',
            capacity: 4000,
            maxCurrent: 2000,
            model: '18900',
            weight: 76,
            height: 90,
            diameter: 18.3,
            nominalVoltage: 1.2,
            minTemperature: -20,
            maxTemperature: 70,
        },
        {
            image: '/images/picture-17.jpeg',
            type: 'Rechargeable',
            family: 'NiMH',
            chemistry: 'NiMH',
            supplier: 'GP',
            name: '300CHT',
            outdoor: 'Y',
            capacity: 3000,
            maxCurrent: 1500,
            model: 'C',
            weight: 71.5,
            height: 50,
            diameter: 25.8,
            nominalVoltage: 1.2,
            minTemperature: -20,
            maxTemperature: 70,
        },
        {
            image: '/images/picture-18.jpeg',
            type: 'Rechargeable',
            family: 'NiMH',
            chemistry: 'NiMH',
            supplier: 'GP',
            name: '700DHT',
            outdoor: 'Y',
            capacity: 7000,
            maxCurrent: 3500,
            model: 'D',
            weight: 146,
            height: 60.5,
            diameter: 33,
            nominalVoltage: 1.2,
            minTemperature: -20,
            maxTemperature: 70,
        },
        // {
        //     image: '/images/picture-1.jpeg',
        //     name: 'GN1604A',
        //     type: 'Non-rechargeable',
        //     chemistry: 'Alkaline',
        //     model: 9,
        //     weight: 47.0,
        //     height: 48.5,
        //     w_idth: 17.5,
        //     lengt: 26.,
        //     diameter: '',
        //     nominalnominalVoltage: 9.0,
        //     indoor: 'Yes',
        //     outdoor: 'Yes',
        //     minTemperature: -20,
        //    maxTemperatureerature: 54,
        //     countInStock: 0
        // },
        // {
        //     image: '/images/picture-1.jpegpicture-2.jpeg',
        //     name: 'GN15A',
        //     type: 'Non-rechargeable',
        //     chemistry: 'Alkaline',
        //     model: 'AA',
        //     weight: 44.0,
        //     height: 50.5,
        //     width: '',
        //     lengt: '',
        //     diameter: 14.5,
        //     nominalnominalVoltage: 1.5,
        //     indoor: 'Yes',
        //     outdoor: 'Yes',
        //     minTemperature: -20,
        //    maxTemperatureerature: 54,
        //     countInStock: 170
        // },
        // {
        //     image: '/images/picture-1.jpegpicture-3.jpeg',
        //     name: 'GN24A',
        //     type: 'Non-rechargeable',
        //     chemistry: 'Alkaline',
        //     model: 'AAA',
        //     weight: 11.4,
        //     height: 44.5,
        //     width: '',
        //     lengt: '',
        //     diameter: 10.5,
        //     nominalnominalVoltage: 1.5,
        //     indoor: 'Yes',
        //     outdoor: 'Yes',
        //     minTemperature: -20,
        //    maxTemperatureerature: 54,
        //     countInStock: 250
        // },
        // {
        //     image: '/images/picture-1.jpegpicture-4.jpeg',
        //     name: 'GPCR123A',
        //     type: 'Non-rechargeable',
        //     chemistry: 'Lithium Manganese Diox_ide',
        //     model: '',
        //     weight: 17.0,
        //     height: 34.5,
        //     width: '',
        //     lengt: '',
        //     diameter: 16.8,
        //     nominalnominalVoltage: 3.0,
        //     indoor: 'No',
        //     outdoor: 'Yes',
        //     minTemperature: -40,
        //    maxTemperatureerature: 60,
        //     countInStock: 0
        // },
        // {
        //     image: '/images/picture-1.jpegpicture-5.jpeg',
        //     name: 'GPCR-V9',
        //     type: 'Non-rechargeable',
        //     chemistry: 'Lithium Manganese Diox_ide',
        //     model: '',
        //     weight: 34.0,
        //     height: 48.5,
        //     w_idth: 17.5,
        //     lengt: 26.5,
        //     diameter: 0,
        //     nominalnominalVoltage: 9.0,
        //     indoor: 'No',
        //     outdoor: 'Yes',
        //     minTemperature: -40,
        //    maxTemperatureerature: 60,
        //     countInStock: 25
        // },
        // {
        //     image: '/images/picture-1.jpegpicture-6.jpeg',
        //     name: 'GP80AAAH',
        //     type: 'Rechargeable',
        //     chemistry: 'NiMH',
        //     model: 'AAA',
        //     weight: 13.0,
        //     height: 43.7,
        //     width: '',
        //     lengt: '',
        //     diameter: 10.5,
        //     nominalnominalVoltage: 1.2,
        //     indoor: 'Yes',
        //     outdoor: 'No',
        //     minTemperature: -20,
        //    maxTemperatureerature: 50,
        //     countInStock: 40
        // },
        // {
        //     image: '/images/picture-1.jpegpicture-7.jpeg',
        //     name: 'GP180AAH',
        //     type: 'Rechargeable',
        //     chemistry: 'NiMH',
        //     model: 'AA',
        //     weight: 28.0,
        //     height: 49.2,
        //     width: '',
        //     lengt: '',
        //     diameter: 14.5,
        //     nominalnominalVoltage: 1.2,
        //     indoor: 'Yes',
        //     outdoor: 'No',
        //     minTemperature: -20,
        //    maxTemperatureerature: 50,
        //     countInStock: 50
        // },
    ]
}
